### ISSUE TITLE
unable to upgrade from .5 to .9 version

### ISSUE THREAD

**Issue by wings007** [biblibre/omeka-s-module-Solr#14]
Hi, I have installed 0.5 with no issue. However, I was unable to upgrade to 0.6 to 0.9. The error I am having is:

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONSTRAINT solr_mapping_fk_solr_node_id'

I checked my MariaDB version is 10.1.

I tried to uninstall 5 and install 0.9 directly, but I still have a similar issue. Can someone help?

**Comment by jajm** [comment]
Hi,

The problem is with this SQL query:
```sql
ALTER TABLE solr_mapping DROP CONSTRAINT solr_mapping_fk_solr_node_id
```

`DROP CONSTRAINT` was only added in MariaDB 10.2.22 and 10.3.13

If you can upgrade MariaDB, then do it. It seems that 10.1 is not maintained anymore. Meanwhile I'll see if I can make a quick fix

**Comment by wings007** [comment]
Hi,

Thank you so much for your help.  I'll try to upgrade our MariaDB to 10.3.

Thank you once again!

**Comment by wings007** [comment]
Hi Jajm,

I upgrade the MariaDB to the latest version but I still have the same issue.

Thank you,
Wing Ho

**Comment by jajm** [comment]
Hi @wings007 

Can you try with the latest version (`master` branch) ? I replaced `DROP CONSTRAINT` by `DROP FOREIGN KEY` in 9226537

**Comment by wings007** [comment]
Hi,

I have similar error:

Doctrine\DBAL\Exception\DriverException
An exception occurred while executing 'ALTER TABLE solr_mapping DROP FOREIGN KEY solr_mapping_fk_solr_node_id': SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `solr_mapping_fk_solr_node_id`; check that it exists

Thanks,
Wing Ho

**Comment by wings007** [comment]
Hi,

I haven't heard from anyone. I was wondering can anyone help me with this issue?  I checked on the table solr_mapping, there's no solr_mapping_fk_solr_node_id property.  Can I just add this column to the table?

Thank you,
Wing Ho

**Comment by wings007** [comment]
I'm not sure either.  Glad this was the fix.  Thank you for your help.
