### ISSUE TITLE
Invalid Number: true for field is_public

### ISSUE THREAD

**Issue by ttgom** [biblibre/omeka-s-module-Solr#15]
I got an error when not logged in to admin dashboard
"ERR (3): SolrServerException: Invalid Number: true for field is_public in /var/www/html/modules/Solr/src/Querier.php:219"

To get facets showing and get rid of that error I had to change line 117 in src/Querier.php file to:
$fq = sprintf('%s:%s', $is_public_field, $isPublic ? '1' : '0');

**Comment by ttgom** [comment]
Works also like this:
$fq = sprintf('%s:%s', $is_public_field, $isPublic ? true : false);
vs original:
$fq = sprintf('%s:%s', $is_public_field, $isPublic ? 'true' : 'false');

**Comment by jajm** [comment]
What do you have in Solr node settings (/admin/solr/node/<node_id>/edit) for the "Is Public field" setting ? It must be a boolean field

**Comment by ttgom** [comment]
is_public

**Comment by jajm** [comment]
Try `is_public_b`. With Solr's default settings, `*_b` fields are boolean
