### ISSUE TITLE
Can't sort asc/desc Query error: Field Title does not exist

### ISSUE THREAD

**Issue by bradgillap** [biblibre/omeka-s-module-Solr#17]
Omeka S 3.2
[Search](https://github.com/biblibre/omeka-s-module-Search) version 0.9.0
[Solr](https://github.com/biblibre/omeka-s-module-Solr) version 0.9.2

Search works with relevance using dcterms_title_txt
Sort field is set to dcterms_title_txt
Source is set to dcterms:title
solr status is OK
Facets are still working properly.

Sorting by asc/desc shows an error 

Query error: Field Title does not exist

URL has &sort=Title%20%20asc

Has been reindexed, no change. Completed without issue.

**Comment by jajm** [comment]
Hi,

It looks like there is an extra space at the end of the search field name. Can you try to remove it and test again ?

Also, are you sure that dcterms_title_txt can be used for sorting ? By default `*_txt` fields are not sortable and  you have to use a `*_txt_sort` field

**Comment by jajm** [comment]
I just pushed 73c5137480ee16177027a9fe1fe4952ae5874eb2 which should fix your problem.
It also prevents to enter an invalid Solr field name

**Comment by bradgillap** [comment]
Sorry, I missed this.  I'll try to report back after I test it hopefully this week.

**Comment by bradgillap** [comment]
Okay so I'm a lot closer than before now. I have to apologize,  I had completely missed the "search" page under modules and realized after my last update that all of my facets had turned off. They are now enabled and search is working.

I'm still having trouble with sort fields though.

I added dcterms_title_txt_sort to the mappings

I also included it on the other page that describes dcterms_title and which mapping to use for sort like you explained.  When I click ascending or descending it doesn't really change the results still.  Feel like I've almost got this. 

![image](https://user-images.githubusercontent.com/1094081/178615749-d47edfee-139b-4f79-8e7b-00894275a1b7.png)

I tried this with plain text or none without improvement.
![image](https://user-images.githubusercontent.com/1094081/178615818-598e29d1-75ed-438e-a0f0-0ba18eee35d3.png)


![image](https://user-images.githubusercontent.com/1094081/178616034-295f83f0-68dc-4465-8e01-615c88701a70.png)


So I think, I'm just misunderstanding something else now.  Given that relevance works on the txt general and your validator wasn't written in vain, I had issues with my titles fields there as well that have now been fixed.

**Comment by bradgillap** [comment]
ohhh okay,

This is becoming a little more clear now after following the article online about adding multistring facets. 

So I had the impression solr does a big reindex of just like the entire content into a database.  I didn't realize you have to add each field first into the module,  then reindex before the solr backend will even show it as a point of interest.

So I think I actually get this now and I think my sort will probably start working after this index is done but I have about 500k items to get through so it'll be a while. :D 

I can already see on the solr backend a new field I added under the module and it is beginning to show results the way I expect in scoring. That's all a good sign at least.

**Comment by bradgillap** [comment]
It would be extremely helpful if there was a doc of the various types of dynamic fields that most folks would commonly might use in omeka as just a starting point. 

So if I had like dcterms_created. Does that mean I would use the pdate in solr as a way index that?

**Comment by bradgillap** [comment]
Okay, It's sorting on title now...  Thank you for taking this journey with me lol.

Still, would love a quick table of dynamic fields and how they might well relate to various dcterm types. It would help a great deal!  

I think... I think we can close this.
