### ISSUE TITLE
getSearchFields() in the Querier doesn't distinguish by node

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [biblibre/omeka-s-module-Solr#20]
Hello,

I just ran into a bug with this module that will only show up if you're using more than one solr node. The `getSearchFields()` [function](https://github.com/biblibre/omeka-s-module-Solr/blob/8f39f39f8229ae43b80f817a4d24bdfe7b569305/src/Querier.php#L368) doesn't distinguish by solr node. When it gets the search fields through the api, it needs to include the solr node id, otherwise you get search fields from other solr nodes, which can cause all sorts of problems:
`$searchFields = $api->search('solr_search_fields')->getContent();`
should be something like:
`$solrNodeId = $this->getAdapterSetting('solr_node_id');
$searchFields = $api->search('solr_search_fields', ['solr_node_id' => $solrNodeId])->getContent();`

Thanks,

Joseph

**Comment by jajm** [comment]
Thanks for reporting this bug. It's fixed in the latest release (0.9.3)

**Comment by fitnycdigitalinitiatives** [comment]
Great, thanks!
