### ISSUE TITLE
Update Search and solr for omeka 4 or maybe provide removal instructions for db.

### ISSUE THREAD

**Issue by bradgillap** [biblibre/omeka-s-module-Solr#23]
Hi,

if you don't uninstall the module prior to upgrade to omeka-s v4, you get a warning message and the system leaves you with no way to remove the module.

![image](https://user-images.githubusercontent.com/1094081/235540224-3aa164ce-9d52-4cab-a746-ccf02196d3b9.png)

**Comment by jajm** [comment]
Just released Search v0.12.0 and Solr v0.10.0 which should work correctly on Omeka S 4.
