### ISSUE TITLE
Allow to configure user and password (was: 401 Unsuccessful ping request)

### ISSUE THREAD

**Issue by mquantin** [biblibre/omeka-s-module-Solr#26]
Hello, 
sorry for this very basic issue. 
I  have a running instance of solr.

I have `Unsuccessful ping request : Response Code 401. HTTP/1.1 401 Unauthorized` as status of the core in the omeka module. 
Seems logical: I can't figure out where to configure login and password for the module to access the core. 

I get results with: `curl --user 'myLogin:myPasswd' 'http://localhost:8983/solr/omeka/select?q=*:*&indent=on&wt=json'`
so the core seems ok. 

maybe I missed a config? maybe I should configure an access to solr for non-authenticated requests? how?

**Comment by jajm** [comment]
Hello,

Solr authentication is not implemented yet but it should be fairly easy to add. I'll try to add it when I have some time

**Comment by mquantin** [comment]
yes ! great! thanks 
it should be a parameter to add in the request header

I can't figure out how to bypass this, and create a core with unauthenticated access (without password). Any help on this ?

**Comment by mquantin** [comment]
OK great! thank you.
the authentification is on the solr side. 
I can't find any time to try it before wednesday.

**Comment by mquantin** [comment]
Sorry for the late reply. 
I'm facing another issue related to authentication: 

In the solr mapping form, I get a js error (in the console) `TypeError: can't access property "fieldTypes", schema is null`
This seems to be related to [this line view/solr/admin/mapping/form.phtml#L44](https://github.com/biblibre/omeka-s-module-Solr/blob/b8a0dd6bc7d85157821a5b1127407693225b0938/view/solr/admin/mapping/form.phtml#L44)

Indeed the schema is accessible with credentials. The folowing bash command works: 
`curl --user 'login:password' 'http://localhost:8983/solr/omeka/schema'`

Maybe something to change in the SolrNodeRepresentation.php file to have credentials in the queries?

**Comment by mquantin** [comment]
any idea about this issue?

**Comment by jajm** [comment]
I added another commit to the `http-authentication` branch for the schema issue.
Can you update and retry ?

**Comment by mquantin** [comment]
🎉 it works ! 🎉  
thank you

**Comment by mquantin** [comment]
maybe this work should be merged with main branch...

**Comment by jajm** [comment]
> maybe this work should be merged with main branch...

Of course. I'll do it soon. Thanks for testing

**Comment by jajm** [comment]
Fixed in [0.14.0](https://github.com/biblibre/omeka-s-module-Solr/releases/tag/v0.14.0)
