### ISSUE TITLE
Unsuccessful ping 

### ISSUE THREAD

**Issue by pprw** [biblibre/omeka-s-module-Solr#3]
I am trying to configure SolrSeearch Omeka S extension. 

I have solr 6.5 running, php 7 and the solr extension installed.

I have fill out the configuration with my value:

![capture d ecran_2018-01-15_10-34-09](https://user-images.githubusercontent.com/5262986/34944538-53216146-fa00-11e7-976c-e9875a7d877f.png)

but I have a statut error:

```
Warning
: SolrClient::ping(): Entity: line 1: parser error : Start tag expected, '<' not found in
/my_site/modules/Solr/src/Api/Representation/SolrNodeRepresentation.php
on line
100


Warning
: SolrClient::ping(): HTTP/1.1 404 Not Found in
/my_site/modules/Solr/src/Api/Representation/SolrNodeRepresentation.php
on line
100

Warning
: SolrClient::ping(): ^ in
/my_site/modules/Solr/src/Api/Representation/SolrNodeRepresentation.php
on line
100


Warning
: SolrClient::ping(): Xpath Error: no elements found in
/my_site/modules/Solr/src/Api/Representation/SolrNodeRepresentation.php
on line
100

Unsuccessful ping request : Response Code 404. HTTP/1.1 404 Not Found 
```

**Comment by jajm** [comment]
Hi pprw,

can you try to remove the trailing slash of the path field (`solr/omeka` instead of `solr/omeka/`) ?

**Comment by pprw** [comment]
Thanks! it was the problem, so simple... (sorry for the thread so).
