### ISSUE TITLE
Configuration process

### ISSUE THREAD

**Issue by pprw** [biblibre/omeka-s-module-Solr#4]
I need some help to configure solr for Omeka S. 

1. I have solr 6.5.0 installed with the php (7) extension.
2. I installed omeka-s-module-Search, omeka-s-module-jQueryUI and omeka-s-module-Solr with no problem.
3. I configure omeka-s-module-Solr (host, port, path), I have "OK" displayed.  I putted "items" for "Champ 'nom de la ressource'" and "solr_field" for "Sites field" randomly. I name this solr "noeud" "default". I just added "dcterms:title" for mapping 
4. In the Search extension configuration page (admin), I added a index. If I launch the indexation process, it never ends.

example:
```
#73
Statut
Starting
Commencé
16 janvier 2018 14:25:00 UTC+00:00
Terminé
[non terminé]
Classe
Search\Job\Index
Propriétaire
myemail@...
Args

{
    "index-id": "1"
}

Log
[Pas de log]

```
5. I created a page (from the search extension options) and added it to the navigation. But I have an error at every request

```
Omeka S rencontre une erreur

SolrServerException
undefined field items

Détails :

SolrServerException: undefined field items in /mysite/modules/Solr/src/Querier.php:130
Stack trace:
#0 /mysite/modules/Solr/src/Querier.php(130): SolrClient->query(Object(SolrQuery))
#1 /mysite/modules/Search/src/Controller/IndexController.php(127): Solr\Querier->query(Object(Search\Query))
#2 /mysite/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Search\Controller\IndexController->searchAction()
#3 /mysite/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#4 /mysite/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /mysite/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#6 /mysite/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 /mysite/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /mysite/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /mysite/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /mysite/index.php(21): Zend\Mvc\Application->run()
#11 {main}
```

What I am doing wrong?

**Comment by jajm** [comment]
I think that
> SolrServerException: undefined field items in /mysite/modules/Solr/src/Querier.php:130

means that there is no Solr field named 'items'.
You may create it in the Solr configuration (not the Omeka S configuration), or use one of the already defined Solr dynamic field.

For instance I use `resource_name_s` for the "Resource name field", and `sites_is` for "Sites field".

**Comment by pprw** [comment]
OK thank you !

I replace the resource name by `resource_name_s` but I have still the error message for the site field. I tried `sites_is` but it creates the same error.

What was the default for the sites field (I don't know how to add field in solr configuration so I would like to use the default one)?

**Comment by jajm** [comment]
Do you still have the `undefined field items` error message ?

**Comment by pprw** [comment]
Yes:

`Omeka S rencontre une erreur

SolrServerException
undefined field sites_is`

**Comment by jajm** [comment]
Did you change the default Solr configuration ?
Can you go to the 'Add a new mapping page' (`/admin/solr/node/<node_id>/mapping/items/add`) and see in the 'Solr field' dropdown list if there is a dynamic field named `*_is (ints)` ?

**Comment by pprw** [comment]
I didn't change the default solr configuration.

If I go the "add new mapping page", I can see two solr field in dropdown menu: *_t (text_en) and *_s (string).

**Comment by jajm** [comment]
Okay, I don't understand why you have only these two fields whereas I have several dozens.
You could add the required dynamic field using the following line in your Solr schema:

```xml
<dynamicField name="*_is" type="ints" indexed="true" stored="true"/>
```

**Comment by pprw** [comment]
Maybe the problem is related to the solr core? I am using a omeka core taken from https://github.com/scholarslab/SolrSearch.

**Comment by jajm** [comment]
Oh okay, don't use that :-)
It's for Omeka Classic only.
I use the default config created by `bin/solr create_core -c <name>`

**Comment by pprw** [comment]
Ok, I am using now a default core create with the command you indicated. I don't have the error message anymore and I see plenty of fields when I go to 'Add a new mapping page'.

However, I also secured my solr installation. The admin interface is now password protected (by modifying jetty files) and the consequence is to block omeka S access to solr. I don't see anywhere to enter my credentials for access to solr.

**Comment by jajm** [comment]
Is it HTTP Basic authentication ?

**Comment by pprw** [comment]
No it is a jetty based authentication (described in the second answer to this question: https://stackoverflow.com/questions/28043957/how-to-set-apache-solr-admin-password).

We tried the HTTP basic authentication by uploading a file security.json in the /etc/ directory but it wasn't working. We run solr 6.5.

**Comment by pprw** [comment]
By trying the HTTP basic authentication, I mean to create a file name security.json in the /etc/ folder and restart solr.

Sorry, it is not related to the omeka S plugin.

security.json:
```
{
"authentication":{
   "class":"solr.BasicAuthPlugin",
   "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}
},
"authorization":{
   "class":"solr.RuleBasedAuthorizationPlugin",
   "permissions":[{"name":"security-edit",
      "role":"admin"}],
   "user-role":{"solr":"admin"}
}}
```

**Comment by jajm** [comment]
Both looks like HTTP Basic Authentication.

I added a way to set a login and a password in the node configuration form, in the git branch `http-auth`. Can you try this ?

**Comment by pprw** [comment]
I changed the server url to have login:passwd@server and it seems to work.

I will try also your solution.

**Comment by pprw** [comment]
Ok I tested the http-auth branch and it is displaying a "OK" on the solr configuration page. However, I try a solr search in the public interface, I obtain:
```

Warning: file_get_contents(http://serveur:16923/solr/ehp/schema): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /mysite/modules/Solr/src/Schema.php on line 31

Warning: Invalid argument supplied for foreach() in /mysite/modules/Solr/src/Schema.php on line 69

Warning: file_get_contents(http://my_serveur:16923/solr/core/schema): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /mysite/modules/Solr/src/Schema.php on line 31

Warning: Invalid argument supplied for foreach() in /mysite/modules/Solr/src/Schema.php on line 112
```

I didn't have this when simply adding the login and password to the url of the server

**Comment by pprw** [comment]
if I use the method which seems to work (login:passwd@server) and launch an indexing process, (1.) the job never ends and (2.) I don't have any result for a solr search (even with "*" as search). In my solr administration interface, I can see the JVM-Memory changing but that's all.

**Comment by pprw** [comment]
also: I just added two facettes (title and date) for testing purpose (see screenshot) but I have no results whatsoever.

I am not sure how to add mapping/facettes, especially what solr field choose and what does the "formateur" field.


![capture d ecran_2018-01-26_16-47-15](https://user-images.githubusercontent.com/5262986/35447793-e77fe82e-02b8-11e8-8b80-a9d1effae7f9.png)
![capture d ecran_2018-01-26_16-48-45](https://user-images.githubusercontent.com/5262986/35447798-ea4ae1a8-02b8-11e8-88a9-09ce7cbabf17.png)

**Comment by pprw** [comment]
Any idea? Maybe the database is too big to let solr finishing indexing?

**Comment by pprw** [comment]
You can close this. It was a problem with solr not indexing.
