### ISSUE TITLE
Facettes splitted in two or more

### ISSUE THREAD

**Issue by pprw** [biblibre/omeka-s-module-Solr#5]
If a facette is composed of several words, they will be splitted.

For example I created a facette with the document type (resource template). I have a document type which is called "Lieux d'archives". I obtain two facettes "Lieux" and "d'archives" with the same results inside.

**Comment by jajm** [comment]
You need to use a field type that doesn't split tokens, like `string` (`*_s`)

**Comment by pprw** [comment]
Ok thank you. You can close this.
