### ISSUE TITLE
Fatal error: Class 'SolrClient' not found

### ISSUE THREAD

**Issue by Numerizen** [biblibre/omeka-s-module-Solr#8]
Hello and thanks for your work on this module.

I'm trying very hard to make it work and failed on too different machines on fresh installations, so I'm pretty sure there's something wrong with the code, maybe with dependency injection ?

The error happens when I try to start the indexing (i.e : everything went fine until then). The task fails immediately and the task's log contains this error :

```
2018-03-09T09:29:04+00:00 INFO (6): Start
2018-03-09T09:29:04+00:00 INFO (6): Index id: 2
Fatal error: Class 'SolrClient' not found
in /var/www/clients/client1/web1/psl/modules/Solr/src/Indexer.php on line 188
```
The php_solr extension is correctly installed and activated (not possible to enable the module otherwise) and a side test script indicates everything is OK with it.

I tried to apply the currently available pull request as a patch (it applied flawlessly)  but it didn't change anything for this matter.

So something is wrong with Omeka-S (last version : 1.0.1), unless I'm missing something, which is always possible. 

In any case, I would be very grateful if you could point me in the right direction or even better, give a solution.

Thanks in advance.

**Comment by jajm** [comment]
You shouldn't be able to enable the module if 'solr' extension is not installed:

https://github.com/biblibre/omeka-s-module-Solr/blob/c9c04706ec5c6e5facbc808dade2d61c1c57bd3f/Module.php#L80

So I suspect that the 'solr' extension is enabled for your webserver, but not for the PHP CLI (indexing process, as all background jobs in Omeka S, is run using the CLI)

**Comment by Numerizen** [comment]
How could I possibly miss that ? You're right, of course, the extension was correctly enabled for web but not for CLI. 

Everything seems fine now. It's indexing as I write.

Thanks a lot. Have a nice day.

**Comment by jajm** [comment]
Great !
